apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: labX-tradr-channel
  namespace: labX-tekton
spec:
  sourceNamespaces:
  - default
  type: Namespace
  pathname: labX-tekton
  gates:
    annotations:
      dev-ready: approved
