apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: labX-tradr-subscription
  namespace: labX-mcm-resources
  labels:
    purpose: labX-tradr
spec:
  channel: labX-tekton/labX-tradr-channel
  placement:
    placementRef:
      name: labX-tradr-placementrule
      kind: PlacementRule
      group: app.ibm.com
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: labX-tradr-mcm
