apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: labX-tradr-application
  namespace: labX-mcm-resources
spec:
  selector:
    matchLabels:
      purpose: labX-tradr
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
